### PR TITLE
Swap umap URL showing more details

### PR DESCRIPTION
**Pull request by harry-wood**
I cloned the umap and added a bunch more information to the map. Here I'm just swapping it in for the zoomed in map appearing on the venue page.

### CODE REVIEW

**Comment by harry-wood** [comment]
Note I added bunch of stuff to the umap, which you can't really see when zoomed in there actually:

screen shot 2018-07-27 at 02 16 03

( http://umap.openstreetmap.fr/en/map/sotm-2018-map_236836#13/45.4720/9.2159  )

I think we should show that kind of map separately somewhere, but for the moment this PR is just adding the details in case people zoom out while viewing the 'venue' page map i.e. The PR doesn't change much. The map on the venue page actually mostly looks unchanged.

**Comment by harry-wood** [comment]
Further note: Regarding the ability of the local team to edit the uMap easily during the conference (which I noticed was discussed over on the other PR)...

With that in mind you might prefer to retain the existing uMap URL (so don't merge this PR) but you could take my efforts and use them a different way, by exporting all my uMap data and importing it onto the existing uMap.... if that makes sense...  Bit more complicated than just merging this though.

**Comment by RobJN** [comment]
Hi @harry-wood. This is nice but I shall leave it to the locals to merge the pull request if they want to. I'm not sure who set up the original uMap and merging this would replace it.

Isn't the easiest option for you to send the link / password to edit this new map to the team (team@stateofthemap.org)? That way we can merge this request and the team has access to the map if they need to make edits.

Maybe once registration is complete, see if you can find @frafra and between the two of you come up with a agreement on this.

**Comment by frafra** [comment]
I did the original uMap, that is incomplete, and I think this pull request is good. I would just replace http with https. If you agree I will do it.

**Comment by frafra** [comment]
We are going to have a social event on Sunday organized by MapTime Milano: https://twitter.com/MaptimeMI/status/1022475984262582272

**Comment by harry-wood** [comment]
Ooh yeah. Well spotted. I've fixed it to be https.

Also I've edited the umap to add Sunday party locations plus Orio al Serio airport (since the venue page mentions it).

**Comment by frafra** [comment]
Thank you @harry-wood :)
@RobJN feel free to revert in case you don't agree with this. And thank you for your work and help :)

**Pull request merged**
