### PR TITLE
Description W019

### PR DESCRIPTION
**Pull request by althio**
fixes https://github.com/osmfoundation/sotm2018/issues/170
related to https://github.com/osmfoundation/sotm2018/issues/169#issuecomment-407190858

### CODE REVIEW

**Comment by althio** [comment]
@frafra @Nakaner program/index.html must also be updated or is it automatic?

**Comment by Nakaner** [comment]
index.html and it/index.html have to be updated to. The toolchain in osmfoundation/sotm2018 does that.

**Comment by althio** [comment]
I do not have access to a suitable environment, I just edited directly on
GitHub website.

Please pick any relevant file and proceed with the toolchain if you have
the opportunity.

>

**Comment by RobJN** [comment]
Fixed in #84.

**Pull request closed without merging**
