### PR TITLE
Add page related to academic track

### PR DESCRIPTION
**Pull request by RobJN**

### CODE REVIEW

**Comment by RobJN** [comment]
Hopefully this works for now. Will also ask comms team to publish to blog.openstreetmap.org.

@MarcoMinghini do you need this adding to the Italian language pages too? If so do you have your page translated or is it ok to leave that in English and just add the link to the Italian front page?

**Comment by RobJN** [comment]
I'm getting a 403 Forbidden error on my new page ( https://2018.stateofthemap.org/academictrack/ ). Clearly I have done something wrong - or it maybe just the server refreshing to the https site.

cc: @mikelmaron @frafra What did I do wrong?

**Comment by mikelmaron** [comment]
fixed here https://github.com/openstreetmap/stateofthemap-2018/pull/26

**Comment by RobJN** [comment]
Obvious when you know how! Thanks :+1:

**Pull request merged**
