### PR TITLE
Replace uMap by self hosted Leaflet and replace Mapbox map by OSMF

### PR DESCRIPTION
**Pull request by Nakaner**
This fixes following issues:

- umap.openstreetmap.fr is overloaded
- umap.openstreetmap.fr is a third-party service and has to be mentioned
  in the privacy policy
- Mapbox is a third-party service and has to be mentioned in the privacy
  policy

This branch is deployed at https://sotm18.michreichert.de/

### CODE REVIEW

**Comment by Nakaner** [comment]
Travel time using M2 was taken from the schedule. Metro route was generated using my railway routing engine (+ a patch permitting `railway=subway`). Pedestrian route from Cadorna to Old Fashion was generated using standard GraphHopper pedestrian routing.

**Comment by mikelmaron** [comment]
I don't understand the issue with "third party service" and privacy policy. 

I'd say it's more important to ensure that the graphic design of the map stays the same but I can not confirm that on your deployment (just says "Hello! This is the web server of Michael Reichert."). Suggest we leave the front page map as it is now, and only replace the umap on the venue page if it's really necessary.

**Comment by frafra** [comment]
I think @Nakaner refers to the fact that the usage of third party cookies should be specified in the privacy policy, due to current EU laws.
Website is down at the moment. I could test it locally, but I would prefer to hear what @mikelmaron says about this, and if everything is ok we can merge it.

**Comment by althio** [comment]
@Nakaner website is not active
If possible, activate it or maybe share screenshots.

We could remove umap if the replacement with leaflet is looking good.

The replacement of this mapbox style by the OSMF style is not something I would want to see.
If the privacy policy is the problem, let us fix that: let us add a privacy policy. Anyway, nobody complained :smiling_imp:

**Comment by Nakaner** [comment]
My test deployment does not have HTTPS: http://sotm18.michreichert.de/ I don't know why I posted the link with HTTPS:

**Comment by mikelmaron** [comment]
Mapbox currently does not do any user tracking of accesses through mapbox-gl-js, so privacy issue is not relevant.

**Comment by Nakaner** [comment]
> I think @Nakaner refers to the fact that the usage of third party cookies should be specified in the privacy policy, due to current EU laws.

Not just cookies but content from a third-party website at all. I don't think that we have to bloat up the [privacy policy of OpenStreetMap](https://wiki.osmfoundation.org/wiki/Privacy_Policy#Data_we_receive_automatically) with a dozen of third party services. It invites readers to ask questions. This can be avoided by simply fixing the root cause.

I removed all Google Fonts from this website a few weeks ago and this pull request is the last step to a compliant website.

**Comment by Nakaner** [comment]
> Mapbox currently does not do any user tracking of accesses through mapbox-gl-js, so privacy issue is not relevant.

Tracking or not does not matter. Mapbox stores data, e.g. log files. Further information is available in [GDPR](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679&from=DE) article 4.

**Comment by mikelmaron** [comment]
At this very late stage, I think it's more important to retain a good looking website, than worry about total compliance. As is, OSMF is still in process of GDPR in general for osm.org, so this is a very very minor issue in comparison. If we had more time, we could look at either technical or legal solutions. Right now, let's leave good enough alone.

**Comment by RobJN** [comment]
Data privacy and third party issues aside, this change creates design issue for mobile (narrow screen) users:

image

In general, mobile has slipped a bit since Mapbox helped us with the first website (in 2016). As noted, this feels like a very late change to be making and it would be courteous to put the question to Mapbox first (given the help we have had and the goodwill we should aim to maintain). I am sure they have had no end of customers ask about GDPR implications and can help with some guidance here.

**Comment by RobJN** [comment]
P.S. In 2016 the local community updated the uMap several times throughout the event. Think it started with pre-event (informal) gathering, then hotel to SotM directions, the SotM to social event, and finally SotM to airport directions. These changes were all easy for the local team to make in uMap. I don't know how we are driving the new map (all Leaflet overlays I think) but we may be moving from a system where many people can edit it, to one where we are dependent on fewer individuals with more experience.

**Comment by Nakaner** [comment]
> Data privacy and third party issues aside, this change creates design issue for mobile (narrow screen) users:

That's a bug, not a feature. I fixed it. You might have to do a forced reload if you still get the old style sheet from the cache.

> I don't know how we are driving the new map (all Leaflet overlays I think) but we may be moving from a system where many people can edit it, to one where we are dependent on fewer individuals with more experience.

It is Leaflet. The data is defined in a [GeoJSON file](https://github.com/Nakaner/stateofthemap-2018/blob/replace-umap/venue/overlay.json).

I wonder (a) if these frequent changes happen at all and (b) if users really look them up on the website.

**Comment by RobJN** [comment]
> I wonder (a) if these frequent changes happen at all

They did in 2016 as I remember watching and thinking "wow, what a call idea". Japan team did videos instead (before and after). That was a "wow" moment as well.

> and (b) if users really look them up on the website

Who knows as we don't run stats on the website these days and I expect all the old stats are now deleted. But it's nice to give the local team the choice.

**Comment by althio** [comment]
About map and design:
OSM standard tile map is not suitable as background, to add overlays on
top. It is already way too loaded graphically.

It would be a poor example of a map for the SotM website.

If we effectively rule out OSM standard: we do need a third-party map
rendering anyway. It could be Mapbox, Stamen, special design, anything.

Even for the umap|leaflet map if it is zoomed out to include conference
site and social event site, it would look better with a simpler map
rendering as background. The umap was using gravitystorm's transport map,
not perfect but better than OSM standard.

**Comment by mikelmaron** [comment]
For 2019, we should document the standards we have for the SotM website map

* cartographically designed to work with design of overall site
* works on web and mobile
* easy for team to modify
* performant
* properly document any third party privacy policies

**Comment by Nakaner** [comment]
I have added the informal Friday evening gathering at/around BASE Milano.

**Comment by harry-wood** [comment]
Ah with that last comment I notice you were having some of the same ideas as me @Nakaner . Yeah I definitely think a map showing the social venue locations is a good idea. I did a different thing, just [fiddling with uMap](https://github.com/openstreetmap/stateofthemap-2018/pull/91) on the venue page to add a bunch of stuff (hotel locations & airports too).

**Comment by Firefishy** [comment]
Closing due to age. If still relevant feel free to rebase and re-open.

**Pull request closed without merging**
